### ISSUE TITLE
Null reference error when sorting by a nullable field

### ISSUE THREAD

**Issue by svtguy88** [apuchkov/knockout-orderable#10]
If you bind the 'field' option to something that could be null, the current code throws a null reference error when trying to run the compare.  The use case for this is trying to sort by a column that is optional.  The issue, and a potential fix for it, are outlined below:

## Current Code ##

```javascript
compare: function (left, right) {
    if (typeof left === 'string' || typeof right === 'string') {
        return left.localeCompare(right); //can't call localeCompare() on a null object
    }
    if (left > right)
        return 1;

     return left < right ? -1 : 0;
    }
```

## Proposed Fix ##
```javascript
compare: function (left, right) {
    if (typeof left === 'string' || typeof right === 'string') {
        return left ? left.localeCompare(right) : 1; //return 1 if left is null
    }
    if (left > right)
        return 1;

     return left < right ? -1 : 0;
    }
```

Thoughts?  If you approve of it, I can submit a pull request.

**Comment by apuchkov** [comment]
Looks good, please go ahead with pull request.

**Comment by svtguy88** [comment]
Pull request submitted.

**Comment by apuchkov** [comment]
Thank you for contribution!
