### ISSUE TITLE
To help make styling easier, the <table> element should have a class added to it.

### ISSUE THREAD

**Issue by svtguy88** [apuchkov/knockout-orderable#12]
I'm using this binding throughout my app, but not all of my tables are orderable.  I see that the `<th>` elements get a "sorted" and either "asc" or "desc" classes when the table is sorted on those columns.  However, there is no class applied to the `<table>` element (and nothing on the non-sorted columns), which makes targeting *only* orderable tables with CSS difficult.

My current solution is to manually apply a class to the `<table>` elements that I'm using this binding on.  What are your thoughts on the binding itself adding a class to the table?

**Comment by apuchkov** [comment]
I think I would leave setting of class element to `<table>` out of the scope of this binding. To me it is easier, more clear and more flexible to add class manually to `<table>`.

**Comment by svtguy88** [comment]
Hmm...alright.  It just seems like there should be a built-in way to target tables that use this binding with CSS.  If you change your mind, I'll probably have it in my fork.
